### ISSUE TITLE
Vue-router 'history' mode not working

### ISSUE THREAD

**Issue by kingzley** [KlausSchaefers/figma-low-code#19]
Hello, thanks for a great tool.
I am trying to use history mode of vue-router, but figma-low-code doesn't update accordingly, it still uses  hash mode routing despite the change I made.

I was wondering if history mode is supported in figma-low-code? If so, how can I use it?

If not, this could be a possible feature request.

Thanks a lot.

**Comment by KlausSchaefers** [comment]
Hi,

I think I fixed it. Can you try out vue-low-code@1.0.1-1.beta?

Cheers,

Klaus

**Comment by kingzley** [comment]
Hello,

I am using vue-low-code@1.0.1-1.beta

I figured the routing works when inputted directly.

But when I click a button to go to another component, it adds hash to the route, hence not working.

It only works when I edit the route URL by removing the hash.

@KlausSchaefers 
Thanks

**Comment by KlausSchaefers** [comment]
Hi,

the new code base should detect if you are using the router in 'history' mode and remove the hashs form the links. The mode should be declared ass

```JS
const router = new VueRouter({
  mode: 'history',
  routes: [...]
})
```



1) Can you delete the package-log.json and the node_modules folder

2) Reinstall all dependencies

Thanks,

Klaus

**Comment by kingzley** [comment]
@KlausSchaefers I have deleted package-lock.json and also node_modules

Then reinstalled.

This is the package-lock reference which shows 1.0.1-beta is used.
```
"vue-low-code": {
      "version": "1.0.1-1.beta",
      "resolved": "https://registry.npmjs.org/vue-low-code/-/vue-low-code-1.0.1-1.beta.tgz",
      "integrity": "sha512-3Gol6q/GFkoBanaF50vGix78GbG8ay7rshmC4GBIn9G/mLUtVjL0NEkylnVxui/DWMr1lrdNBpEf0lJ4AXpqyw==",
      "requires": {
        "@mdi/font": "^4.9.95"
      }
    }
```

And in the router file:
`const router = new VueRouter({
  mode: 'history',
  routes
})`

But it still not working. It adds hash to the route. But when I edit the route url, it works well. But when I click to navigate to a component it adds hash to the url which makes it fail.

**Comment by KlausSchaefers** [comment]
can you open the dev console in the browser. You should see something like

'''
QUX.mounted() > Launch router with history 
'''

**Comment by kingzley** [comment]
@KlausSchaefers Nope. I don't see that in the console.
I'm using Figma not Quant-UX  though.

**Comment by KlausSchaefers** [comment]
Figma wraps Quant-UX.. so you should have seen that.... Strange. can you check if the router object on your page has the mode set?

```
mounted () {
  console.debug(this.$router.mode)
  console.debug(this.$router)
}
```

**Comment by kingzley** [comment]
Ya.

`console.log(this.$router.mode)`
> history

`console.log(this.$router)`
> VueRouter Object

However, `console.debug` doesn't return anything.

**Comment by KlausSchaefers** [comment]
Hmmm, that is strange. can you share your project?

**Comment by kingzley** [comment]
Wow. Thanks for the effort @KlausSchaefers I really appreciate.

I have created temporal repo and figma document.

Figma link: https://www.figma.com/file/uKgt9PzMeazuh8SqXJQoVs/Figma-low-code-route-test?node-id=0%3A1

Repo link: https://github.com/kingzley/figma-low-code-test

**Comment by KlausSchaefers** [comment]
For me this works. The history mode is detected and the links are correct[
<img width="1545" alt="Screen Shot 2021-05-14 at 11 10 14 PM" src="https://user-images.githubusercontent.com/7108416/118332034-c044ce80-b509-11eb-82c7-0b5a069e43e5.png">
<img width="1545" alt="Screen Shot 2021-05-14 at 11 11 07 PM" src="https://user-images.githubusercontent.com/7108416/118332048-c3d85580-b509-11eb-98af-3b62b4c66a12.png">

](url)

**Comment by KlausSchaefers** [comment]
<img width="1545" alt="Screen Shot 2021-05-14 at 11 11 07 PM" src="https://user-images.githubusercontent.com/7108416/118332145-e66a6e80-b509-11eb-8da0-059d942480ba.png">

**Comment by kingzley** [comment]
Ya. **Contact Us** is strange,
Try clicking on **Login** or **SignUp** for example.

**Comment by kingzley** [comment]
Hello @KlausSchaefers 
Were you able to see the routing issue when clicking on Login, SignUP and other buttons on your end?

**Comment by KlausSchaefers** [comment]
Yes. The generated URLs did not contain the # ... see the screen shot.

**Comment by kingzley** [comment]
From the screenshot only the ContactUs element is in an anchor tag. 

But other elements such as **Login** and **Signup** isn't.

Is there any particular reason why this is the case? Because it includes the hash when those buttons are clicked. Please check again to confirm

**Comment by KlausSchaefers** [comment]
Thanks, I found the issue. Nested elements are transformed into divs, and the link is set in JavaScript. There I didn't check for the correct mode. I think it is fixed in 1.0.13. Can you update the lib

```
npm update cue-low-code@1.0.13
```


Klaus

**Comment by kingzley** [comment]
@KlausSchaefers Thanks a lot.  🙏

It works now.

The issue can be closed now.

**Comment by KlausSchaefers** [comment]
Hi,

I found some other bugs in your design, e.g. the line height and missing font imports. I added this in the latest release

```
npm update cue-low-code@1.0.14
```

Could you verify that fixes?

**Comment by kingzley** [comment]
**`No matching version found for vue-low-code@1.0.14`**

Version 1.0.14 not updated yet.

**Comment by KlausSchaefers** [comment]
Ups, did not push to NPM... try now :D

**Comment by kingzley** [comment]
It works.

I just noticed that it doesn't import the font colors.
Is that a bug or that feature is not available now?

**Comment by KlausSchaefers** [comment]
You mean the blue underscores? This is still a missing feature.... Rich text is not yet supported!

**Comment by KlausSchaefers** [comment]
Feel free to open a bug for that...

**Comment by kingzley** [comment]
> You mean the blue underscores? This is still a missing feature.... Rich text is not yet supported!

Yes. Exactly.

> Feel free to open a bug for that...

Oh Ok. Thank you.

**Comment by kingzley** [comment]
Hi @KlausSchaefers 
I also think this repo should be updated with the latest vue-low-code version in package,json so users don't encounter the bugs that have been resolved.
